// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPutNotificationReadParams creates a new PutNotificationReadParams object
// no default values defined in spec.
func NewPutNotificationReadParams() PutNotificationReadParams {

	return PutNotificationReadParams{}
}

// PutNotificationReadParams contains all the bound params for the put notification read operation
// typically these are obtained from a http.Request
//
// swagger:parameters putNotificationRead
type PutNotificationReadParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	NotificationID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutNotificationReadParams() beforehand.
func (o *PutNotificationReadParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rNotificationID, rhkNotificationID, _ := route.Params.GetOK("notification_id")
	if err := o.bindNotificationID(rNotificationID, rhkNotificationID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNotificationID binds and validates parameter NotificationID from path.
func (o *PutNotificationReadParams) bindNotificationID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.NotificationID = raw

	return nil
}
