// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gamersnote.com/v1/utils"
)

// PutNotificationReadHandlerFunc turns a function with the right signature into a put notification read handler
type PutNotificationReadHandlerFunc func(PutNotificationReadParams, *utils.TokenPayload) middleware.Responder

// Handle executing the request and returning a response
func (fn PutNotificationReadHandlerFunc) Handle(params PutNotificationReadParams, principal *utils.TokenPayload) middleware.Responder {
	return fn(params, principal)
}

// PutNotificationReadHandler interface for that can handle valid put notification read params
type PutNotificationReadHandler interface {
	Handle(PutNotificationReadParams, *utils.TokenPayload) middleware.Responder
}

// NewPutNotificationRead creates a new http.Handler for the put notification read operation
func NewPutNotificationRead(ctx *middleware.Context, handler PutNotificationReadHandler) *PutNotificationRead {
	return &PutNotificationRead{Context: ctx, Handler: handler}
}

/*PutNotificationRead swagger:route PUT /users/me/notifications/{notification_id}/read notification putNotificationRead

PutNotificationRead put notification read API

*/
type PutNotificationRead struct {
	Context *middleware.Context
	Handler PutNotificationReadHandler
}

func (o *PutNotificationRead) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutNotificationReadParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *utils.TokenPayload
	if uprinc != nil {
		principal = uprinc.(*utils.TokenPayload) // this is really a utils.TokenPayload, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
