// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutNotificationReadHandlerFunc turns a function with the right signature into a put notification read handler
type PutNotificationReadHandlerFunc func(PutNotificationReadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutNotificationReadHandlerFunc) Handle(params PutNotificationReadParams) middleware.Responder {
	return fn(params)
}

// PutNotificationReadHandler interface for that can handle valid put notification read params
type PutNotificationReadHandler interface {
	Handle(PutNotificationReadParams) middleware.Responder
}

// NewPutNotificationRead creates a new http.Handler for the put notification read operation
func NewPutNotificationRead(ctx *middleware.Context, handler PutNotificationReadHandler) *PutNotificationRead {
	return &PutNotificationRead{Context: ctx, Handler: handler}
}

/*PutNotificationRead swagger:route PUT /users/me/notifications/{notification_id}/read notification putNotificationRead

PutNotificationRead put notification read API

*/
type PutNotificationRead struct {
	Context *middleware.Context
	Handler PutNotificationReadHandler
}

func (o *PutNotificationRead) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutNotificationReadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
