// Code generated by go-swagger; DO NOT EDIT.

// Package restapi GamersNoteAPI
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
