// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GamersNoteAPI",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticles",
        "parameters": [
          {
            "type": "integer",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "keyword",
            "in": "query"
          },
          {
            "type": "string",
            "name": "order",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "article"
        ],
        "operationId": "postArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/articles/{article_id}": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticle",
        "responses": {
          "200": {
            "description": "Get article",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "article"
        ],
        "operationId": "putArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "article"
        ],
        "operationId": "deleteArticle",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/articles/{article_id}/comments": {
      "get": {
        "tags": [
          "comment"
        ],
        "operationId": "getComments",
        "responses": {
          "200": {
            "description": "Successed",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/comment"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "comment"
        ],
        "operationId": "postComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/comment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/comments/{comment_id}": {
      "put": {
        "tags": [
          "comment"
        ],
        "operationId": "putComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/comment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "comment"
        ],
        "operationId": "deleteComment",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "comment_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/status": {
      "get": {
        "tags": [
          "healthcheck"
        ],
        "operationId": "healthcheck",
        "responses": {
          "200": {
            "description": "healthy"
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": [
          "user"
        ],
        "operationId": "postUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password",
                "username"
              ],
              "properties": {
                "email": {
                  "$ref": "#/definitions/email"
                },
                "password": {
                  "$ref": "#/definitions/password"
                },
                "username": {
                  "$ref": "#/definitions/username"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "409": {
            "description": "Duplicated",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "tags": [
          "user"
        ],
        "operationId": "getMe",
        "responses": {
          "200": {
            "description": "get me",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "user"
        ],
        "operationId": "putUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/email/verified": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserEmailVerified",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "code",
                "uid"
              ],
              "properties": {
                "code": {
                  "type": "string"
                },
                "uid": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows": {
      "get": {
        "tags": [
          "follow"
        ],
        "operationId": "getFollows",
        "responses": {
          "200": {
            "description": "get follows",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/user"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getFollowsArticles",
        "parameters": [
          {
            "type": "number",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "get follows articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/{user_id}": {
      "put": {
        "tags": [
          "follow"
        ],
        "operationId": "putFollow",
        "parameters": [
          {
            "type": "string",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successed"
          }
        }
      }
    },
    "/users/me/images": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "image"
        ],
        "operationId": "uploadImage",
        "parameters": [
          {
            "type": "file",
            "name": "image",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "required": [
                "url"
              ],
              "properties": {
                "url": {
                  "type": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/liked/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getLikedArticles",
        "responses": {
          "200": {
            "description": "get liked articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/likes/{article_id}": {
      "get": {
        "tags": [
          "like"
        ],
        "operationId": "getLike",
        "responses": {
          "200": {
            "description": "Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "NotFound"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "like"
        ],
        "operationId": "putLike",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "like"
        ],
        "operationId": "deleteLike",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/notifications": {
      "get": {
        "tags": [
          "notification"
        ],
        "operationId": "getNotifications",
        "responses": {
          "200": {
            "description": "get notifications",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/notification"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/notifications/{notification_id}/read": {
      "put": {
        "tags": [
          "notification"
        ],
        "operationId": "putNotificationRead",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "notification_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/password": {
      "put": {
        "tags": [
          "user"
        ],
        "operationId": "putPassword",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "password"
              ],
              "properties": {
                "code": {
                  "type": "string"
                },
                "password": {
                  "$ref": "#/definitions/password"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/password/reset": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserPasswordReset",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email"
              ],
              "properties": {
                "email": {
                  "$ref": "#/definitions/email"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/signined": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserSignined",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "email": {
                  "$ref": "#/definitions/email"
                },
                "password": {
                  "$ref": "#/definitions/password"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/signouted": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserSignouted",
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/stocks": {
      "get": {
        "tags": [
          "stock"
        ],
        "operationId": "getStockedArticles",
        "responses": {
          "200": {
            "description": "get stocks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/stocks/{article_id}": {
      "put": {
        "tags": [
          "stock"
        ],
        "operationId": "putStock",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "stock"
        ],
        "operationId": "deleteStock",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/verified": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserVerified",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "code",
                "username"
              ],
              "properties": {
                "code": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/{username}": {
      "get": {
        "tags": [
          "user"
        ],
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "gamersnote_idを指定してユーザーを取得",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "username",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{username}/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getTheUsersArticles",
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get articles by user",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "article": {
      "type": "object",
      "required": [
        "thumbnail_url",
        "title",
        "body"
      ],
      "properties": {
        "article_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 1,
          "readOnly": true
        },
        "body": {
          "x-order": 4,
          "$ref": "#/definitions/base_html"
        },
        "comments": {
          "x-order": 6,
          "$ref": "#/definitions/comments"
        },
        "created_at": {
          "x-order": 7,
          "$ref": "#/definitions/base_date"
        },
        "like_count": {
          "x-order": 5,
          "$ref": "#/definitions/base_count"
        },
        "thumbnail_url": {
          "x-order": 2,
          "$ref": "#/definitions/img_url"
        },
        "title": {
          "x-order": 3,
          "$ref": "#/definitions/article_title"
        },
        "updated_at": {
          "x-order": 8,
          "$ref": "#/definitions/base_date"
        }
      }
    },
    "article_title": {
      "type": "string",
      "maxLength": 50,
      "minLength": 2
    },
    "base_count": {
      "type": "integer",
      "readOnly": true
    },
    "base_date": {
      "type": "string",
      "format": "date",
      "readOnly": true
    },
    "base_html": {
      "type": "string"
    },
    "base_id": {
      "type": "string",
      "readOnly": true
    },
    "comment": {
      "type": "object",
      "required": [
        "body"
      ],
      "properties": {
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 2,
          "readOnly": true
        },
        "body": {
          "type": "string",
          "x-order": 3
        },
        "comment_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 4,
          "readOnly": true
        },
        "replies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/comment"
          },
          "x-order": 1,
          "readOnly": true
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/comment"
      },
      "readOnly": true
    },
    "email": {
      "type": "string",
      "pattern": "[A-Za-z0-9\\-\\.\\_]+@[A-Za-z0-9\\-\\._]+\\.[A-Za-z]+"
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64",
          "x-order": 0
        },
        "message": {
          "type": "string",
          "x-order": 1
        }
      }
    },
    "img_url": {
      "type": "string"
    },
    "notification": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "x-order": 3,
          "readOnly": true
        },
        "category": {
          "type": "string",
          "x-order": 2,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 5,
          "readOnly": true
        },
        "is_read": {
          "type": "boolean",
          "x-order": 4,
          "readOnly": true
        },
        "notification_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "sender": {
          "x-order": 1,
          "$ref": "#/definitions/user"
        }
      }
    },
    "password": {
      "type": "string",
      "pattern": "[A-Za-z0-9\\_]{6,20}"
    },
    "profile_message": {
      "type": "string",
      "maxLength": 200
    },
    "user": {
      "type": "object",
      "required": [
        "username",
        "email"
      ],
      "properties": {
        "avatar_url": {
          "x-order": 3,
          "$ref": "#/definitions/img_url"
        },
        "email": {
          "x-order": 2,
          "$ref": "#/definitions/email"
        },
        "message": {
          "x-order": 4,
          "$ref": "#/definitions/profile_message"
        },
        "registered_at": {
          "x-order": 5,
          "$ref": "#/definitions/base_date"
        },
        "user_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "username": {
          "x-order": 1,
          "$ref": "#/definitions/username"
        }
      }
    },
    "username": {
      "type": "string",
      "pattern": "[A-Za-z0-9\\_]{4,12}"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GamersNoteAPI",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticles",
        "parameters": [
          {
            "type": "integer",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "name": "keyword",
            "in": "query"
          },
          {
            "type": "string",
            "name": "order",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "article"
        ],
        "operationId": "postArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/articles/{article_id}": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticle",
        "responses": {
          "200": {
            "description": "Get article",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "article"
        ],
        "operationId": "putArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "article"
        ],
        "operationId": "deleteArticle",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/articles/{article_id}/comments": {
      "get": {
        "tags": [
          "comment"
        ],
        "operationId": "getComments",
        "responses": {
          "200": {
            "description": "Successed",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/comment"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "comment"
        ],
        "operationId": "postComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/comment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/comments/{comment_id}": {
      "put": {
        "tags": [
          "comment"
        ],
        "operationId": "putComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/comment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "comment"
        ],
        "operationId": "deleteComment",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "comment_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/status": {
      "get": {
        "tags": [
          "healthcheck"
        ],
        "operationId": "healthcheck",
        "responses": {
          "200": {
            "description": "healthy"
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": [
          "user"
        ],
        "operationId": "postUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password",
                "username"
              ],
              "properties": {
                "email": {
                  "$ref": "#/definitions/email"
                },
                "password": {
                  "$ref": "#/definitions/password"
                },
                "username": {
                  "$ref": "#/definitions/username"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "409": {
            "description": "Duplicated",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "tags": [
          "user"
        ],
        "operationId": "getMe",
        "responses": {
          "200": {
            "description": "get me",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "user"
        ],
        "operationId": "putUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/email/verified": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserEmailVerified",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "code",
                "uid"
              ],
              "properties": {
                "code": {
                  "type": "string"
                },
                "uid": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows": {
      "get": {
        "tags": [
          "follow"
        ],
        "operationId": "getFollows",
        "responses": {
          "200": {
            "description": "get follows",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/user"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getFollowsArticles",
        "parameters": [
          {
            "type": "number",
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "get follows articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/{user_id}": {
      "put": {
        "tags": [
          "follow"
        ],
        "operationId": "putFollow",
        "parameters": [
          {
            "type": "string",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successed"
          }
        }
      }
    },
    "/users/me/images": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "image"
        ],
        "operationId": "uploadImage",
        "parameters": [
          {
            "type": "file",
            "name": "image",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "required": [
                "url"
              ],
              "properties": {
                "url": {
                  "type": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/liked/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getLikedArticles",
        "responses": {
          "200": {
            "description": "get liked articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/likes/{article_id}": {
      "get": {
        "tags": [
          "like"
        ],
        "operationId": "getLike",
        "responses": {
          "200": {
            "description": "Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "NotFound"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "like"
        ],
        "operationId": "putLike",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "like"
        ],
        "operationId": "deleteLike",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/notifications": {
      "get": {
        "tags": [
          "notification"
        ],
        "operationId": "getNotifications",
        "responses": {
          "200": {
            "description": "get notifications",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/notification"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/notifications/{notification_id}/read": {
      "put": {
        "tags": [
          "notification"
        ],
        "operationId": "putNotificationRead",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "notification_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/password": {
      "put": {
        "tags": [
          "user"
        ],
        "operationId": "putPassword",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "password"
              ],
              "properties": {
                "code": {
                  "type": "string"
                },
                "password": {
                  "$ref": "#/definitions/password"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/password/reset": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserPasswordReset",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email"
              ],
              "properties": {
                "email": {
                  "$ref": "#/definitions/email"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/signined": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserSignined",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "email": {
                  "$ref": "#/definitions/email"
                },
                "password": {
                  "$ref": "#/definitions/password"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/signouted": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserSignouted",
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/stocks": {
      "get": {
        "tags": [
          "stock"
        ],
        "operationId": "getStockedArticles",
        "responses": {
          "200": {
            "description": "get stocks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/stocks/{article_id}": {
      "put": {
        "tags": [
          "stock"
        ],
        "operationId": "putStock",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "stock"
        ],
        "operationId": "deleteStock",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/verified": {
      "patch": {
        "tags": [
          "user"
        ],
        "operationId": "patchUserVerified",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "code",
                "username"
              ],
              "properties": {
                "code": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/{username}": {
      "get": {
        "tags": [
          "user"
        ],
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "gamersnote_idを指定してユーザーを取得",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "username",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{username}/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getTheUsersArticles",
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get articles by user",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "article": {
      "type": "object",
      "required": [
        "thumbnail_url",
        "title",
        "body"
      ],
      "properties": {
        "article_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 1,
          "readOnly": true
        },
        "body": {
          "x-order": 4,
          "$ref": "#/definitions/base_html"
        },
        "comments": {
          "x-order": 6,
          "$ref": "#/definitions/comments"
        },
        "created_at": {
          "x-order": 7,
          "$ref": "#/definitions/base_date"
        },
        "like_count": {
          "x-order": 5,
          "$ref": "#/definitions/base_count"
        },
        "thumbnail_url": {
          "x-order": 2,
          "$ref": "#/definitions/img_url"
        },
        "title": {
          "x-order": 3,
          "$ref": "#/definitions/article_title"
        },
        "updated_at": {
          "x-order": 8,
          "$ref": "#/definitions/base_date"
        }
      }
    },
    "article_title": {
      "type": "string",
      "maxLength": 50,
      "minLength": 2
    },
    "base_count": {
      "type": "integer",
      "readOnly": true
    },
    "base_date": {
      "type": "string",
      "format": "date",
      "readOnly": true
    },
    "base_html": {
      "type": "string"
    },
    "base_id": {
      "type": "string",
      "readOnly": true
    },
    "comment": {
      "type": "object",
      "required": [
        "body"
      ],
      "properties": {
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 2,
          "readOnly": true
        },
        "body": {
          "type": "string",
          "x-order": 3
        },
        "comment_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 4,
          "readOnly": true
        },
        "replies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/comment"
          },
          "x-order": 1,
          "readOnly": true
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/comment"
      },
      "readOnly": true
    },
    "email": {
      "type": "string",
      "pattern": "[A-Za-z0-9\\-\\.\\_]+@[A-Za-z0-9\\-\\._]+\\.[A-Za-z]+"
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64",
          "x-order": 0
        },
        "message": {
          "type": "string",
          "x-order": 1
        }
      }
    },
    "img_url": {
      "type": "string"
    },
    "notification": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "x-order": 3,
          "readOnly": true
        },
        "category": {
          "type": "string",
          "x-order": 2,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 5,
          "readOnly": true
        },
        "is_read": {
          "type": "boolean",
          "x-order": 4,
          "readOnly": true
        },
        "notification_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "sender": {
          "x-order": 1,
          "$ref": "#/definitions/user"
        }
      }
    },
    "password": {
      "type": "string",
      "pattern": "[A-Za-z0-9\\_]{6,20}"
    },
    "profile_message": {
      "type": "string",
      "maxLength": 200,
      "minLength": 0
    },
    "user": {
      "type": "object",
      "required": [
        "username",
        "email"
      ],
      "properties": {
        "avatar_url": {
          "x-order": 3,
          "$ref": "#/definitions/img_url"
        },
        "email": {
          "x-order": 2,
          "$ref": "#/definitions/email"
        },
        "message": {
          "x-order": 4,
          "$ref": "#/definitions/profile_message"
        },
        "registered_at": {
          "x-order": 5,
          "$ref": "#/definitions/base_date"
        },
        "user_id": {
          "x-order": 0,
          "$ref": "#/definitions/base_id"
        },
        "username": {
          "x-order": 1,
          "$ref": "#/definitions/username"
        }
      }
    },
    "username": {
      "type": "string",
      "pattern": "[A-Za-z0-9\\_]{4,12}"
    }
  }
}`))
}
