// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GamersNoteAPI",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticles",
        "parameters": [
          {
            "type": "string",
            "name": "since",
            "in": "query"
          },
          {
            "type": "string",
            "name": "keyword",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "postArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/articles/{article_id}": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticle",
        "responses": {
          "200": {
            "description": "Get article",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "putArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "deleteArticle",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/articles/{article_id}/comments": {
      "get": {
        "tags": [
          "comment"
        ],
        "operationId": "getComments",
        "responses": {
          "200": {
            "description": "Successed",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/comment"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "comment"
        ],
        "operationId": "postComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/articles/{article_id}/comments/{comment_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "comment"
        ],
        "operationId": "putComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/comment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "comment"
        ],
        "operationId": "deleteComment",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "comment_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "postUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "409": {
            "description": "Duplicated",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "getMe",
        "responses": {
          "200": {
            "description": "get me",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "putUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "follow"
        ],
        "operationId": "getFollows",
        "responses": {
          "200": {
            "description": "get follows",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/user"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/articles": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "getFollowsArticles",
        "parameters": [
          {
            "type": "string",
            "name": "since",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "get follows articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/{user_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "follow"
        ],
        "operationId": "putFollow",
        "parameters": [
          {
            "type": "string",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successed"
          }
        }
      }
    },
    "/users/me/likes": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "like"
        ],
        "operationId": "getLikedArticles",
        "responses": {
          "200": {
            "description": "get liked articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/likes/{article_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "like"
        ],
        "operationId": "putLike",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "like"
        ],
        "operationId": "deleteLike",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/notifications": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "notification"
        ],
        "operationId": "getNotifications",
        "responses": {
          "200": {
            "description": "get notifications",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/notification"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/notifications/{notification_id}/read": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "notification"
        ],
        "operationId": "putNotificationRead",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "notification_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/stocks": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "stock"
        ],
        "operationId": "getStockedArticles",
        "responses": {
          "200": {
            "description": "get stocks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/stocks/{article_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "stock"
        ],
        "operationId": "putStock",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "stock"
        ],
        "operationId": "deleteStock",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{gamersnote_id}": {
      "get": {
        "tags": [
          "user"
        ],
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "gamersnote_idを指定してユーザーを取得",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "gamersnote_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{gamersnote_id}/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getTheUsersArticles",
        "parameters": [
          {
            "type": "string",
            "name": "gamersnote_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get articles by user",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "article": {
      "type": "object",
      "required": [
        "thumbnail_url",
        "title",
        "body",
        "is_published"
      ],
      "properties": {
        "article_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 1,
          "readOnly": true
        },
        "body": {
          "type": "string",
          "x-order": 4
        },
        "comments": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/comment"
          },
          "x-order": 6,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 9,
          "readOnly": true
        },
        "is_published": {
          "type": "boolean",
          "x-order": 7
        },
        "like_count": {
          "type": "integer",
          "x-order": 5,
          "readOnly": true
        },
        "published_at": {
          "type": "string",
          "format": "date",
          "x-order": 8,
          "readOnly": true
        },
        "thumbnail_url": {
          "type": "string",
          "x-order": 2
        },
        "title": {
          "type": "string",
          "x-order": 3
        },
        "updated_at": {
          "type": "string",
          "format": "date",
          "x-order": 10,
          "readOnly": true
        }
      }
    },
    "comment": {
      "type": "object",
      "required": [
        "body"
      ],
      "properties": {
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 2,
          "readOnly": true
        },
        "body": {
          "type": "string",
          "x-order": 3
        },
        "comment_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 4,
          "readOnly": true
        },
        "replies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/comment"
          },
          "x-order": 1,
          "readOnly": true
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64",
          "x-order": 0
        },
        "message": {
          "type": "string",
          "x-order": 1
        }
      }
    },
    "notification": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "x-order": 3,
          "readOnly": true
        },
        "category": {
          "type": "string",
          "x-order": 2,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 5,
          "readOnly": true
        },
        "is_read": {
          "type": "boolean",
          "x-order": 4,
          "readOnly": true
        },
        "notification_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "sender": {
          "x-order": 1,
          "$ref": "#/definitions/user"
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "gamersnote_id",
        "username",
        "avatar_url",
        "message"
      ],
      "properties": {
        "avatar_url": {
          "type": "string",
          "x-order": 3
        },
        "gamersnote_id": {
          "type": "string",
          "maxLength": 12,
          "minLength": 4,
          "pattern": "[A-Za-z0-9 ]{4,12}",
          "x-order": 1
        },
        "message": {
          "type": "string",
          "maxLength": 200,
          "x-order": 4
        },
        "registered_at": {
          "type": "string",
          "format": "date",
          "x-order": 5,
          "readOnly": true
        },
        "user_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "username": {
          "type": "string",
          "maxLength": 20,
          "minLength": 4,
          "x-order": 2
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "GamersNoteAPI",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticles",
        "parameters": [
          {
            "type": "string",
            "name": "since",
            "in": "query"
          },
          {
            "type": "string",
            "name": "keyword",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "postArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/articles/{article_id}": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getArticle",
        "responses": {
          "200": {
            "description": "Get article",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "putArticle",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/article"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "deleteArticle",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/articles/{article_id}/comments": {
      "get": {
        "tags": [
          "comment"
        ],
        "operationId": "getComments",
        "responses": {
          "200": {
            "description": "Successed",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/comment"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "comment"
        ],
        "operationId": "postComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/article"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/articles/{article_id}/comments/{comment_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "comment"
        ],
        "operationId": "putComment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/comment"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "comment"
        ],
        "operationId": "deleteComment",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "comment_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "postUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "409": {
            "description": "Duplicated",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "getMe",
        "responses": {
          "200": {
            "description": "get me",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "putUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "user"
        ],
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "follow"
        ],
        "operationId": "getFollows",
        "responses": {
          "200": {
            "description": "get follows",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/user"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/articles": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "article"
        ],
        "operationId": "getFollowsArticles",
        "parameters": [
          {
            "type": "string",
            "name": "since",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "get follows articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/follows/{user_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "follow"
        ],
        "operationId": "putFollow",
        "parameters": [
          {
            "type": "string",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successed"
          }
        }
      }
    },
    "/users/me/likes": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "like"
        ],
        "operationId": "getLikedArticles",
        "responses": {
          "200": {
            "description": "get liked articles",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/likes/{article_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "like"
        ],
        "operationId": "putLike",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "like"
        ],
        "operationId": "deleteLike",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/notifications": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "notification"
        ],
        "operationId": "getNotifications",
        "responses": {
          "200": {
            "description": "get notifications",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/notification"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/notifications/{notification_id}/read": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "notification"
        ],
        "operationId": "putNotificationRead",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "notification_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/me/stocks": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "stock"
        ],
        "operationId": "getStockedArticles",
        "responses": {
          "200": {
            "description": "get stocks",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/users/me/stocks/{article_id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "stock"
        ],
        "operationId": "putStock",
        "responses": {
          "200": {
            "description": "Successed"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "stock"
        ],
        "operationId": "deleteStock",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "article_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{gamersnote_id}": {
      "get": {
        "tags": [
          "user"
        ],
        "operationId": "getUser",
        "responses": {
          "200": {
            "description": "gamersnote_idを指定してユーザーを取得",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "gamersnote_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{gamersnote_id}/articles": {
      "get": {
        "tags": [
          "article"
        ],
        "operationId": "getTheUsersArticles",
        "parameters": [
          {
            "type": "string",
            "name": "gamersnote_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "get articles by user",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/article"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "article": {
      "type": "object",
      "required": [
        "thumbnail_url",
        "title",
        "body",
        "is_published"
      ],
      "properties": {
        "article_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 1,
          "readOnly": true
        },
        "body": {
          "type": "string",
          "x-order": 4
        },
        "comments": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/comment"
          },
          "x-order": 6,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 9,
          "readOnly": true
        },
        "is_published": {
          "type": "boolean",
          "x-order": 7
        },
        "like_count": {
          "type": "integer",
          "x-order": 5,
          "readOnly": true
        },
        "published_at": {
          "type": "string",
          "format": "date",
          "x-order": 8,
          "readOnly": true
        },
        "thumbnail_url": {
          "type": "string",
          "x-order": 2
        },
        "title": {
          "type": "string",
          "x-order": 3
        },
        "updated_at": {
          "type": "string",
          "format": "date",
          "x-order": 10,
          "readOnly": true
        }
      }
    },
    "comment": {
      "type": "object",
      "required": [
        "body"
      ],
      "properties": {
        "author": {
          "allOf": [
            {
              "$ref": "#/definitions/user"
            }
          ],
          "x-order": 2,
          "readOnly": true
        },
        "body": {
          "type": "string",
          "x-order": 3
        },
        "comment_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 4,
          "readOnly": true
        },
        "replies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/comment"
          },
          "x-order": 1,
          "readOnly": true
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64",
          "x-order": 0
        },
        "message": {
          "type": "string",
          "x-order": 1
        }
      }
    },
    "notification": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "x-order": 3,
          "readOnly": true
        },
        "category": {
          "type": "string",
          "x-order": 2,
          "readOnly": true
        },
        "created_at": {
          "type": "string",
          "format": "date",
          "x-order": 5,
          "readOnly": true
        },
        "is_read": {
          "type": "boolean",
          "x-order": 4,
          "readOnly": true
        },
        "notification_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "sender": {
          "x-order": 1,
          "$ref": "#/definitions/user"
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "gamersnote_id",
        "username",
        "avatar_url",
        "message"
      ],
      "properties": {
        "avatar_url": {
          "type": "string",
          "x-order": 3
        },
        "gamersnote_id": {
          "type": "string",
          "maxLength": 12,
          "minLength": 4,
          "pattern": "[A-Za-z0-9 ]{4,12}",
          "x-order": 1
        },
        "message": {
          "type": "string",
          "maxLength": 200,
          "minLength": 0,
          "x-order": 4
        },
        "registered_at": {
          "type": "string",
          "format": "date",
          "x-order": 5,
          "readOnly": true
        },
        "user_id": {
          "type": "string",
          "x-order": 0,
          "readOnly": true
        },
        "username": {
          "type": "string",
          "maxLength": 20,
          "minLength": 4,
          "x-order": 2
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
