/* tslint:disable */
/* eslint-disable */
/**
 * GamersNoteAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    readonly notificationId?: string;
    /**
     * 
     * @type {User}
     * @memberof Notification
     */
    sender?: User;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    readonly category?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    readonly body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    readonly isRead?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    readonly createdAt?: Date;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notificationId': !exists(json, 'notification_id') ? undefined : json['notification_id'],
        'sender': !exists(json, 'sender') ? undefined : UserFromJSON(json['sender']),
        'category': !exists(json, 'category') ? undefined : json['category'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'isRead': !exists(json, 'is_read') ? undefined : json['is_read'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function NotificationToJSON(value?: Notification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sender': UserToJSON(value.sender),
    };
}


