/* tslint:disable */
/* eslint-disable */
/**
 * GamersNoteAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    readonly userId?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    gamersnoteId: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    readonly registeredAt?: Date;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
        'gamersnoteId': json['gamersnote_id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'avatarUrl': !exists(json, 'avatar_url') ? undefined : json['avatar_url'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'registeredAt': !exists(json, 'registered_at') ? undefined : (new Date(json['registered_at'])),
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gamersnote_id': value.gamersnoteId,
        'username': value.username,
        'avatar_url': value.avatarUrl,
        'message': value.message,
    };
}


