// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// DeleteCommentNoContentCode is the HTTP code returned for type DeleteCommentNoContent
const DeleteCommentNoContentCode int = 204

/*DeleteCommentNoContent Deleted

swagger:response deleteCommentNoContent
*/
type DeleteCommentNoContent struct {
}

// NewDeleteCommentNoContent creates DeleteCommentNoContent with default headers values
func NewDeleteCommentNoContent() *DeleteCommentNoContent {

	return &DeleteCommentNoContent{}
}

// WriteResponse to the client
func (o *DeleteCommentNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteCommentDefault error

swagger:response deleteCommentDefault
*/
type DeleteCommentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteCommentDefault creates DeleteCommentDefault with default headers values
func NewDeleteCommentDefault(code int) *DeleteCommentDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteCommentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete comment default response
func (o *DeleteCommentDefault) WithStatusCode(code int) *DeleteCommentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete comment default response
func (o *DeleteCommentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete comment default response
func (o *DeleteCommentDefault) WithPayload(payload *models.Error) *DeleteCommentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete comment default response
func (o *DeleteCommentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCommentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
