// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostCommentHandlerFunc turns a function with the right signature into a post comment handler
type PostCommentHandlerFunc func(PostCommentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCommentHandlerFunc) Handle(params PostCommentParams) middleware.Responder {
	return fn(params)
}

// PostCommentHandler interface for that can handle valid post comment params
type PostCommentHandler interface {
	Handle(PostCommentParams) middleware.Responder
}

// NewPostComment creates a new http.Handler for the post comment operation
func NewPostComment(ctx *middleware.Context, handler PostCommentHandler) *PostComment {
	return &PostComment{Context: ctx, Handler: handler}
}

/*PostComment swagger:route POST /articles/{article_id}/comments comment postComment

PostComment post comment API

*/
type PostComment struct {
	Context *middleware.Context
	Handler PostCommentHandler
}

func (o *PostComment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostCommentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
