// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"gamersnote.com/v1/models"
)

// NewPutCommentParams creates a new PutCommentParams object
// no default values defined in spec.
func NewPutCommentParams() PutCommentParams {

	return PutCommentParams{}
}

// PutCommentParams contains all the bound params for the put comment operation
// typically these are obtained from a http.Request
//
// swagger:parameters putComment
type PutCommentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ArticleID string
	/*
	  Required: true
	  In: body
	*/
	Body *models.Comment
	/*
	  Required: true
	  In: path
	*/
	CommentID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutCommentParams() beforehand.
func (o *PutCommentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rArticleID, rhkArticleID, _ := route.Params.GetOK("article_id")
	if err := o.bindArticleID(rArticleID, rhkArticleID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Comment
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	rCommentID, rhkCommentID, _ := route.Params.GetOK("comment_id")
	if err := o.bindCommentID(rCommentID, rhkCommentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindArticleID binds and validates parameter ArticleID from path.
func (o *PutCommentParams) bindArticleID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ArticleID = raw

	return nil
}

// bindCommentID binds and validates parameter CommentID from path.
func (o *PutCommentParams) bindCommentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.CommentID = raw

	return nil
}
