// Code generated by go-swagger; DO NOT EDIT.

package follow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// GetFollowsOKCode is the HTTP code returned for type GetFollowsOK
const GetFollowsOKCode int = 200

/*GetFollowsOK get follows

swagger:response getFollowsOK
*/
type GetFollowsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.User `json:"body,omitempty"`
}

// NewGetFollowsOK creates GetFollowsOK with default headers values
func NewGetFollowsOK() *GetFollowsOK {

	return &GetFollowsOK{}
}

// WithPayload adds the payload to the get follows o k response
func (o *GetFollowsOK) WithPayload(payload []*models.User) *GetFollowsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get follows o k response
func (o *GetFollowsOK) SetPayload(payload []*models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFollowsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetFollowsDefault error

swagger:response getFollowsDefault
*/
type GetFollowsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFollowsDefault creates GetFollowsDefault with default headers values
func NewGetFollowsDefault(code int) *GetFollowsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetFollowsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get follows default response
func (o *GetFollowsDefault) WithStatusCode(code int) *GetFollowsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get follows default response
func (o *GetFollowsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get follows default response
func (o *GetFollowsDefault) WithPayload(payload *models.Error) *GetFollowsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get follows default response
func (o *GetFollowsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFollowsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
