// Code generated by go-swagger; DO NOT EDIT.

package follow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gamersnote.com/v1/utils"
)

// GetFollowsHandlerFunc turns a function with the right signature into a get follows handler
type GetFollowsHandlerFunc func(GetFollowsParams, *utils.TokenPayload) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFollowsHandlerFunc) Handle(params GetFollowsParams, principal *utils.TokenPayload) middleware.Responder {
	return fn(params, principal)
}

// GetFollowsHandler interface for that can handle valid get follows params
type GetFollowsHandler interface {
	Handle(GetFollowsParams, *utils.TokenPayload) middleware.Responder
}

// NewGetFollows creates a new http.Handler for the get follows operation
func NewGetFollows(ctx *middleware.Context, handler GetFollowsHandler) *GetFollows {
	return &GetFollows{Context: ctx, Handler: handler}
}

/*GetFollows swagger:route GET /users/me/follows follow getFollows

GetFollows get follows API

*/
type GetFollows struct {
	Context *middleware.Context
	Handler GetFollowsHandler
}

func (o *GetFollows) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFollowsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *utils.TokenPayload
	if uprinc != nil {
		principal = uprinc.(*utils.TokenPayload) // this is really a utils.TokenPayload, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
