// Code generated by go-swagger; DO NOT EDIT.

package follow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutFollowOKCode is the HTTP code returned for type PutFollowOK
const PutFollowOKCode int = 200

/*PutFollowOK Successed

swagger:response putFollowOK
*/
type PutFollowOK struct {
}

// NewPutFollowOK creates PutFollowOK with default headers values
func NewPutFollowOK() *PutFollowOK {

	return &PutFollowOK{}
}

// WriteResponse to the client
func (o *PutFollowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
