// Code generated by go-swagger; DO NOT EDIT.

package like

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gamersnote.com/v1/utils"
)

// DeleteLikeHandlerFunc turns a function with the right signature into a delete like handler
type DeleteLikeHandlerFunc func(DeleteLikeParams, *utils.TokenPayload) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteLikeHandlerFunc) Handle(params DeleteLikeParams, principal *utils.TokenPayload) middleware.Responder {
	return fn(params, principal)
}

// DeleteLikeHandler interface for that can handle valid delete like params
type DeleteLikeHandler interface {
	Handle(DeleteLikeParams, *utils.TokenPayload) middleware.Responder
}

// NewDeleteLike creates a new http.Handler for the delete like operation
func NewDeleteLike(ctx *middleware.Context, handler DeleteLikeHandler) *DeleteLike {
	return &DeleteLike{Context: ctx, Handler: handler}
}

/*DeleteLike swagger:route DELETE /users/me/likes/{article_id} like deleteLike

DeleteLike delete like API

*/
type DeleteLike struct {
	Context *middleware.Context
	Handler DeleteLikeHandler
}

func (o *DeleteLike) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteLikeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *utils.TokenPayload
	if uprinc != nil {
		principal = uprinc.(*utils.TokenPayload) // this is really a utils.TokenPayload, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
