// Code generated by go-swagger; DO NOT EDIT.

package like

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// DeleteLikeNoContentCode is the HTTP code returned for type DeleteLikeNoContent
const DeleteLikeNoContentCode int = 204

/*DeleteLikeNoContent Deleted

swagger:response deleteLikeNoContent
*/
type DeleteLikeNoContent struct {
}

// NewDeleteLikeNoContent creates DeleteLikeNoContent with default headers values
func NewDeleteLikeNoContent() *DeleteLikeNoContent {

	return &DeleteLikeNoContent{}
}

// WriteResponse to the client
func (o *DeleteLikeNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteLikeDefault error

swagger:response deleteLikeDefault
*/
type DeleteLikeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteLikeDefault creates DeleteLikeDefault with default headers values
func NewDeleteLikeDefault(code int) *DeleteLikeDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteLikeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete like default response
func (o *DeleteLikeDefault) WithStatusCode(code int) *DeleteLikeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete like default response
func (o *DeleteLikeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete like default response
func (o *DeleteLikeDefault) WithPayload(payload *models.Error) *DeleteLikeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete like default response
func (o *DeleteLikeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteLikeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
