// Code generated by go-swagger; DO NOT EDIT.

package like

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// GetLikedArticlesOKCode is the HTTP code returned for type GetLikedArticlesOK
const GetLikedArticlesOKCode int = 200

/*GetLikedArticlesOK get liked articles

swagger:response getLikedArticlesOK
*/
type GetLikedArticlesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Article `json:"body,omitempty"`
}

// NewGetLikedArticlesOK creates GetLikedArticlesOK with default headers values
func NewGetLikedArticlesOK() *GetLikedArticlesOK {

	return &GetLikedArticlesOK{}
}

// WithPayload adds the payload to the get liked articles o k response
func (o *GetLikedArticlesOK) WithPayload(payload []*models.Article) *GetLikedArticlesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get liked articles o k response
func (o *GetLikedArticlesOK) SetPayload(payload []*models.Article) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLikedArticlesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Article, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetLikedArticlesDefault error

swagger:response getLikedArticlesDefault
*/
type GetLikedArticlesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLikedArticlesDefault creates GetLikedArticlesDefault with default headers values
func NewGetLikedArticlesDefault(code int) *GetLikedArticlesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLikedArticlesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get liked articles default response
func (o *GetLikedArticlesDefault) WithStatusCode(code int) *GetLikedArticlesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get liked articles default response
func (o *GetLikedArticlesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get liked articles default response
func (o *GetLikedArticlesDefault) WithPayload(payload *models.Error) *GetLikedArticlesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get liked articles default response
func (o *GetLikedArticlesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLikedArticlesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
