// Code generated by go-swagger; DO NOT EDIT.

package like

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// PutLikeOKCode is the HTTP code returned for type PutLikeOK
const PutLikeOKCode int = 200

/*PutLikeOK Successed

swagger:response putLikeOK
*/
type PutLikeOK struct {
}

// NewPutLikeOK creates PutLikeOK with default headers values
func NewPutLikeOK() *PutLikeOK {

	return &PutLikeOK{}
}

// WriteResponse to the client
func (o *PutLikeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*PutLikeDefault error

swagger:response putLikeDefault
*/
type PutLikeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutLikeDefault creates PutLikeDefault with default headers values
func NewPutLikeDefault(code int) *PutLikeDefault {
	if code <= 0 {
		code = 500
	}

	return &PutLikeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put like default response
func (o *PutLikeDefault) WithStatusCode(code int) *PutLikeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put like default response
func (o *PutLikeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put like default response
func (o *PutLikeDefault) WithPayload(payload *models.Error) *PutLikeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put like default response
func (o *PutLikeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutLikeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
