// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// BaseID base id
//
// swagger:model base_id
type BaseID string

// Validate validates this base id
func (m BaseID) Validate(formats strfmt.Registry) error {
	return nil
}
