// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BaseDate base date
//
// swagger:model base_date
type BaseDate strfmt.Date

// UnmarshalJSON sets a BaseDate value from JSON input
func (m *BaseDate) UnmarshalJSON(b []byte) error {
	return ((*strfmt.Date)(m)).UnmarshalJSON(b)
}

// MarshalJSON retrieves a BaseDate value as JSON output
func (m BaseDate) MarshalJSON() ([]byte, error) {
	return (strfmt.Date(m)).MarshalJSON()
}

// Validate validates this base date
func (m BaseDate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.FormatOf("", "body", "date", strfmt.Date(m).String(), formats); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *BaseDate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseDate) UnmarshalBinary(b []byte) error {
	var res BaseDate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
