// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// BaseCount base count
//
// swagger:model base_count
type BaseCount int64

// Validate validates this base count
func (m BaseCount) Validate(formats strfmt.Registry) error {
	return nil
}
