// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// BaseHTML base html
//
// swagger:model base_html
type BaseHTML string

// Validate validates this base html
func (m BaseHTML) Validate(formats strfmt.Registry) error {
	return nil
}
