// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewUploadImageParams creates a new UploadImageParams object
// no default values defined in spec.
func NewUploadImageParams() UploadImageParams {

	return UploadImageParams{}
}

// UploadImageParams contains all the bound params for the upload image operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadImage
type UploadImageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: formData
	*/
	Image io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadImageParams() beforehand.
func (o *UploadImageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	image, imageHeader, err := r.FormFile("image")
	if err != nil && err != http.ErrMissingFile {
		res = append(res, errors.New(400, "reading file %q failed: %v", "image", err))
	} else if err == http.ErrMissingFile {
		// no-op for missing but optional file parameter
	} else if err := o.bindImage(image, imageHeader); err != nil {
		res = append(res, err)
	} else {
		o.Image = &runtime.File{Data: image, Header: imageHeader}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindImage binds file parameter Image.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadImageParams) bindImage(file multipart.File, header *multipart.FileHeader) error {
	return nil
}
