// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// PatchUserEmailVerifiedOKCode is the HTTP code returned for type PatchUserEmailVerifiedOK
const PatchUserEmailVerifiedOKCode int = 200

/*PatchUserEmailVerifiedOK Success

swagger:response patchUserEmailVerifiedOK
*/
type PatchUserEmailVerifiedOK struct {
}

// NewPatchUserEmailVerifiedOK creates PatchUserEmailVerifiedOK with default headers values
func NewPatchUserEmailVerifiedOK() *PatchUserEmailVerifiedOK {

	return &PatchUserEmailVerifiedOK{}
}

// WriteResponse to the client
func (o *PatchUserEmailVerifiedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*PatchUserEmailVerifiedDefault error

swagger:response patchUserEmailVerifiedDefault
*/
type PatchUserEmailVerifiedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUserEmailVerifiedDefault creates PatchUserEmailVerifiedDefault with default headers values
func NewPatchUserEmailVerifiedDefault(code int) *PatchUserEmailVerifiedDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchUserEmailVerifiedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch user email verified default response
func (o *PatchUserEmailVerifiedDefault) WithStatusCode(code int) *PatchUserEmailVerifiedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch user email verified default response
func (o *PatchUserEmailVerifiedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch user email verified default response
func (o *PatchUserEmailVerifiedDefault) WithPayload(payload *models.Error) *PatchUserEmailVerifiedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user email verified default response
func (o *PatchUserEmailVerifiedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserEmailVerifiedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
