// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// PatchUserSigninedOKCode is the HTTP code returned for type PatchUserSigninedOK
const PatchUserSigninedOKCode int = 200

/*PatchUserSigninedOK Success

swagger:response patchUserSigninedOK
*/
type PatchUserSigninedOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPatchUserSigninedOK creates PatchUserSigninedOK with default headers values
func NewPatchUserSigninedOK() *PatchUserSigninedOK {

	return &PatchUserSigninedOK{}
}

// WithPayload adds the payload to the patch user signined o k response
func (o *PatchUserSigninedOK) WithPayload(payload *models.User) *PatchUserSigninedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user signined o k response
func (o *PatchUserSigninedOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserSigninedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchUserSigninedDefault error

swagger:response patchUserSigninedDefault
*/
type PatchUserSigninedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUserSigninedDefault creates PatchUserSigninedDefault with default headers values
func NewPatchUserSigninedDefault(code int) *PatchUserSigninedDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchUserSigninedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch user signined default response
func (o *PatchUserSigninedDefault) WithStatusCode(code int) *PatchUserSigninedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch user signined default response
func (o *PatchUserSigninedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch user signined default response
func (o *PatchUserSigninedDefault) WithPayload(payload *models.Error) *PatchUserSigninedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user signined default response
func (o *PatchUserSigninedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserSigninedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
