// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"gamersnote.com/v1/models"
)

// PatchUserPasswordResetHandlerFunc turns a function with the right signature into a patch user password reset handler
type PatchUserPasswordResetHandlerFunc func(PatchUserPasswordResetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUserPasswordResetHandlerFunc) Handle(params PatchUserPasswordResetParams) middleware.Responder {
	return fn(params)
}

// PatchUserPasswordResetHandler interface for that can handle valid patch user password reset params
type PatchUserPasswordResetHandler interface {
	Handle(PatchUserPasswordResetParams) middleware.Responder
}

// NewPatchUserPasswordReset creates a new http.Handler for the patch user password reset operation
func NewPatchUserPasswordReset(ctx *middleware.Context, handler PatchUserPasswordResetHandler) *PatchUserPasswordReset {
	return &PatchUserPasswordReset{Context: ctx, Handler: handler}
}

/*PatchUserPasswordReset swagger:route PATCH /users/me/password/reset user patchUserPasswordReset

PatchUserPasswordReset patch user password reset API

*/
type PatchUserPasswordReset struct {
	Context *middleware.Context
	Handler PatchUserPasswordResetHandler
}

func (o *PatchUserPasswordReset) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchUserPasswordResetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PatchUserPasswordResetBody patch user password reset body
//
// swagger:model PatchUserPasswordResetBody
type PatchUserPasswordResetBody struct {

	// email
	// Required: true
	Email models.Email `json:"email"`
}

// Validate validates this patch user password reset body
func (o *PatchUserPasswordResetBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchUserPasswordResetBody) validateEmail(formats strfmt.Registry) error {

	if err := o.Email.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("body" + "." + "email")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PatchUserPasswordResetBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchUserPasswordResetBody) UnmarshalBinary(b []byte) error {
	var res PatchUserPasswordResetBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
