// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// PatchUserSignoutedOKCode is the HTTP code returned for type PatchUserSignoutedOK
const PatchUserSignoutedOKCode int = 200

/*PatchUserSignoutedOK Success

swagger:response patchUserSignoutedOK
*/
type PatchUserSignoutedOK struct {
}

// NewPatchUserSignoutedOK creates PatchUserSignoutedOK with default headers values
func NewPatchUserSignoutedOK() *PatchUserSignoutedOK {

	return &PatchUserSignoutedOK{}
}

// WriteResponse to the client
func (o *PatchUserSignoutedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*PatchUserSignoutedDefault error

swagger:response patchUserSignoutedDefault
*/
type PatchUserSignoutedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUserSignoutedDefault creates PatchUserSignoutedDefault with default headers values
func NewPatchUserSignoutedDefault(code int) *PatchUserSignoutedDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchUserSignoutedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch user signouted default response
func (o *PatchUserSignoutedDefault) WithStatusCode(code int) *PatchUserSignoutedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch user signouted default response
func (o *PatchUserSignoutedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch user signouted default response
func (o *PatchUserSignoutedDefault) WithPayload(payload *models.Error) *PatchUserSignoutedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user signouted default response
func (o *PatchUserSignoutedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserSignoutedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
