// Code generated by go-swagger; DO NOT EDIT.

package article

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// DeleteArticleNoContentCode is the HTTP code returned for type DeleteArticleNoContent
const DeleteArticleNoContentCode int = 204

/*DeleteArticleNoContent Deleted

swagger:response deleteArticleNoContent
*/
type DeleteArticleNoContent struct {
}

// NewDeleteArticleNoContent creates DeleteArticleNoContent with default headers values
func NewDeleteArticleNoContent() *DeleteArticleNoContent {

	return &DeleteArticleNoContent{}
}

// WriteResponse to the client
func (o *DeleteArticleNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteArticleDefault error

swagger:response deleteArticleDefault
*/
type DeleteArticleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteArticleDefault creates DeleteArticleDefault with default headers values
func NewDeleteArticleDefault(code int) *DeleteArticleDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteArticleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete article default response
func (o *DeleteArticleDefault) WithStatusCode(code int) *DeleteArticleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete article default response
func (o *DeleteArticleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete article default response
func (o *DeleteArticleDefault) WithPayload(payload *models.Error) *DeleteArticleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete article default response
func (o *DeleteArticleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteArticleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
