// Code generated by go-swagger; DO NOT EDIT.

package article

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// GetFollowsArticlesOKCode is the HTTP code returned for type GetFollowsArticlesOK
const GetFollowsArticlesOKCode int = 200

/*GetFollowsArticlesOK get follows articles

swagger:response getFollowsArticlesOK
*/
type GetFollowsArticlesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Article `json:"body,omitempty"`
}

// NewGetFollowsArticlesOK creates GetFollowsArticlesOK with default headers values
func NewGetFollowsArticlesOK() *GetFollowsArticlesOK {

	return &GetFollowsArticlesOK{}
}

// WithPayload adds the payload to the get follows articles o k response
func (o *GetFollowsArticlesOK) WithPayload(payload []*models.Article) *GetFollowsArticlesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get follows articles o k response
func (o *GetFollowsArticlesOK) SetPayload(payload []*models.Article) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFollowsArticlesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Article, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetFollowsArticlesDefault error

swagger:response getFollowsArticlesDefault
*/
type GetFollowsArticlesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFollowsArticlesDefault creates GetFollowsArticlesDefault with default headers values
func NewGetFollowsArticlesDefault(code int) *GetFollowsArticlesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetFollowsArticlesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get follows articles default response
func (o *GetFollowsArticlesDefault) WithStatusCode(code int) *GetFollowsArticlesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get follows articles default response
func (o *GetFollowsArticlesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get follows articles default response
func (o *GetFollowsArticlesDefault) WithPayload(payload *models.Error) *GetFollowsArticlesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get follows articles default response
func (o *GetFollowsArticlesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFollowsArticlesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
