// Code generated by go-swagger; DO NOT EDIT.

package article

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// GetTheUsersArticlesOKCode is the HTTP code returned for type GetTheUsersArticlesOK
const GetTheUsersArticlesOKCode int = 200

/*GetTheUsersArticlesOK get articles by user

swagger:response getTheUsersArticlesOK
*/
type GetTheUsersArticlesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Article `json:"body,omitempty"`
}

// NewGetTheUsersArticlesOK creates GetTheUsersArticlesOK with default headers values
func NewGetTheUsersArticlesOK() *GetTheUsersArticlesOK {

	return &GetTheUsersArticlesOK{}
}

// WithPayload adds the payload to the get the users articles o k response
func (o *GetTheUsersArticlesOK) WithPayload(payload []*models.Article) *GetTheUsersArticlesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get the users articles o k response
func (o *GetTheUsersArticlesOK) SetPayload(payload []*models.Article) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTheUsersArticlesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Article, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetTheUsersArticlesDefault error

swagger:response getTheUsersArticlesDefault
*/
type GetTheUsersArticlesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTheUsersArticlesDefault creates GetTheUsersArticlesDefault with default headers values
func NewGetTheUsersArticlesDefault(code int) *GetTheUsersArticlesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTheUsersArticlesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get the users articles default response
func (o *GetTheUsersArticlesDefault) WithStatusCode(code int) *GetTheUsersArticlesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get the users articles default response
func (o *GetTheUsersArticlesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get the users articles default response
func (o *GetTheUsersArticlesDefault) WithPayload(payload *models.Error) *GetTheUsersArticlesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get the users articles default response
func (o *GetTheUsersArticlesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTheUsersArticlesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
