// Code generated by go-swagger; DO NOT EDIT.

package article

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gamersnote.com/v1/models"
)

// PostArticleCreatedCode is the HTTP code returned for type PostArticleCreated
const PostArticleCreatedCode int = 201

/*PostArticleCreated Created

swagger:response postArticleCreated
*/
type PostArticleCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Article `json:"body,omitempty"`
}

// NewPostArticleCreated creates PostArticleCreated with default headers values
func NewPostArticleCreated() *PostArticleCreated {

	return &PostArticleCreated{}
}

// WithPayload adds the payload to the post article created response
func (o *PostArticleCreated) WithPayload(payload *models.Article) *PostArticleCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post article created response
func (o *PostArticleCreated) SetPayload(payload *models.Article) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostArticleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostArticleDefault error

swagger:response postArticleDefault
*/
type PostArticleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostArticleDefault creates PostArticleDefault with default headers values
func NewPostArticleDefault(code int) *PostArticleDefault {
	if code <= 0 {
		code = 500
	}

	return &PostArticleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post article default response
func (o *PostArticleDefault) WithStatusCode(code int) *PostArticleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post article default response
func (o *PostArticleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post article default response
func (o *PostArticleDefault) WithPayload(payload *models.Error) *PostArticleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post article default response
func (o *PostArticleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostArticleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
