// Code generated by go-swagger; DO NOT EDIT.

package article

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gamersnote.com/v1/utils"
)

// PutArticleHandlerFunc turns a function with the right signature into a put article handler
type PutArticleHandlerFunc func(PutArticleParams, *utils.TokenPayload) middleware.Responder

// Handle executing the request and returning a response
func (fn PutArticleHandlerFunc) Handle(params PutArticleParams, principal *utils.TokenPayload) middleware.Responder {
	return fn(params, principal)
}

// PutArticleHandler interface for that can handle valid put article params
type PutArticleHandler interface {
	Handle(PutArticleParams, *utils.TokenPayload) middleware.Responder
}

// NewPutArticle creates a new http.Handler for the put article operation
func NewPutArticle(ctx *middleware.Context, handler PutArticleHandler) *PutArticle {
	return &PutArticle{Context: ctx, Handler: handler}
}

/*PutArticle swagger:route PUT /articles/{article_id} article putArticle

PutArticle put article API

*/
type PutArticle struct {
	Context *middleware.Context
	Handler PutArticleHandler
}

func (o *PutArticle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutArticleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *utils.TokenPayload
	if uprinc != nil {
		principal = uprinc.(*utils.TokenPayload) // this is really a utils.TokenPayload, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
