// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gamersnote.com/v1/utils"
)

// PutStockHandlerFunc turns a function with the right signature into a put stock handler
type PutStockHandlerFunc func(PutStockParams, *utils.TokenPayload) middleware.Responder

// Handle executing the request and returning a response
func (fn PutStockHandlerFunc) Handle(params PutStockParams, principal *utils.TokenPayload) middleware.Responder {
	return fn(params, principal)
}

// PutStockHandler interface for that can handle valid put stock params
type PutStockHandler interface {
	Handle(PutStockParams, *utils.TokenPayload) middleware.Responder
}

// NewPutStock creates a new http.Handler for the put stock operation
func NewPutStock(ctx *middleware.Context, handler PutStockHandler) *PutStock {
	return &PutStock{Context: ctx, Handler: handler}
}

/*PutStock swagger:route PUT /users/me/stocks/{article_id} stock putStock

PutStock put stock API

*/
type PutStock struct {
	Context *middleware.Context
	Handler PutStockHandler
}

func (o *PutStock) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutStockParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *utils.TokenPayload
	if uprinc != nil {
		principal = uprinc.(*utils.TokenPayload) // this is really a utils.TokenPayload, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
